### ISSUE TITLE
Too Many 502 Error Responses

### ISSUE THREAD

**Issue by typicalTYLER** [typicalTYLER/CO2PeakFinder#3]
2019-06-09 02:40:00.100204: [1560048000.1002045, 447.1560915726605, 85.39010814249363]
2019-06-09 02:45:00.100173: [1560048300.1001735, 447.1560915726605, 85.39010814249363]
2019-06-09 02:50:00.100169: [1560048600.1001687, 444.90899064431096, 84.95690845512418]
2019-06-09 02:55:00.100169: [1560048900.1001692, 444.90899064431096, 84.95690845512418]
2019-06-09 03:00:00.100164: [1560049200.1001644, 444.90899064431096, 84.95690845512418]
2019-06-09 03:05:00.100171: [1560049500.1001713, 442.7655006357549, 84.53799769601844]
Traceback (most recent call last):
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.co2signal.com', port=443): Max retries exceeded with url: /v1/latest?countryCode=US-TX (Caused by ResponseError('too many 502 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data_collector.py", line 63, in <module>
    country_code=args.country_code), headers={'auth-token': os.environ['CO2SIGNAL_API_KEY']})
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.co2signal.com', port=443): Max retries exceeded with url: /v1/latest?countryCode=US-TX (Caused by ResponseError('too many 502 error responses',))
tylerbusby333@instance-1:~/CO2PeakFinder$

**Comment by typicalTYLER** [comment]
And another:

```
2019-06-24 10:30:00.100231: [1561372200.1002312, 436.29634762230035, 83.27322538637314]
Traceback (most recent call last):
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.co2signal.com', port=443): Max retries exceeded with url: /v1/latest?countryCode=US-TX (Caused by ResponseError('too many 502 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data_collector.py", line 63, in <module>
    country_code=args.country_code), headers={'auth-token': os.environ['CO2SIGNAL_API_KEY']})
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/tylerbusby333/.local/lib/python3.5/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.co2signal.com', port=443): Max retries exceeded with url: /v1/latest?countryCode=US-TX (Caused by ResponseError('too many 502 error responses',))
```
